name:                claire
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/claire#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           myuon
category:            Language
extra-source-files:
- README.md

default-extensions:
- Strict
- PatternSynonyms

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.10
  - trifecta

executables:
  claire:
    source-dirs:      src
    main:             Main.hs
