name:                claire
version:             0.4.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/claire#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           myuon
category:            Language
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.10
- trifecta
- lens
- mtl
- monad-coroutine
- exceptions

default-extensions:
- PatternSynonyms
- Rank2Types

ghc-options:
- -Wunused-imports
- -Wunused-local-binds

extra-source-files:
- src/Claire/Laire/Lexer.x
- src/Claire/Laire/Parser.y

library:
  source-dirs: src

  build-tools:
  - alex
  - happy

  dependencies:
  - array

  other-modules:
  - Claire.Laire.Lexer
  - Claire.Laire.Parser

executables:
  claire:
    source-dirs:      app
    main:             Main.hs
    dependencies:
    - claire
    - ansi-wl-pprint

tests:
  claire-test:
    source-dirs:      test
    main:	      Driver.hs
    dependencies:
    - claire
    - tasty-hunit
    - tasty

